config/routes.rb
Rails.application.routes.draw do
  root to: "agents#index"
  resource :agent, only: [:show, :create, :update, :destroy]
  resources :contracts
  resources :ships
  resources :waypoints
end

app/models/agent.rb
class Agent < ApplicationRecord
  attr_accessor :account_id,
                :symbol,
                :headquarters,
                :credits,
                :starting_faction,
                :ship_count

  RESOURCE_URL = "https://api.spacetraders.io/v2/my/agent"

  class << self
    def fetch(token)
      payload = ApiResource.fetch("https://api.spacetraders.io/v2/my/agent", token)
      new(**payload)
    end

    def register(symbol)
      response =
        Faraday.post(
          "https://api.spacetraders.io/v2/register",
          "{\"symbol\":\"#{symbol}\",\"faction\":\"COSMIC\"}",
          "Content-Type" => "application/json"
        )
      agent = JSON.parse(response.body)
      Agent.create(name: symbol, token: agent["data"]["token"])
    end
  end
end

app/models/api_resource.rb
class ApiResource
  class << self
    def fetch(url, token)
      api_response =
        Faraday.get(url, nil, { "Authorization" => "Bearer #{token}" })
      parsed_body = JSON.parse(api_response.body).deep_transform_keys(&:underscore)
      parsed_body["data"]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contract.rb
class Contract
  include ActiveModel::API

  RESOURCE_URL = "https://api.spacetraders.io/v2/my/contracts"

  attr_accessor :id,
                :faction_symbol,
                :type,
                :terms,
                :accepted,
                :fulfilled,
                :expiration,
                :deadline_to_accept

  class << self
    def fetch_all(token)
      payloads = ApiResource.fetch(RESOURCE_URL, token)
      payloads.map { |payload| new(**payload) }
    end

    def accept(id, token)
      Faraday.post(
        "#{RESOURCE_URL}/#{id}/accept",
        nil,
        { "Authorization" => "Bearer #{token}" }
      )
    end
  end
end

app/models/ship.rb
class Ship
  include ActiveModel::API

  RESOURCE_URL = "https://api.spacetraders.io/v2/my/ships"

  attr_accessor :symbol,
                :registration,
                :nav,
                :crew,
                :frame,
                :reactor,
                :engine,
                :cooldown,
                :modules,
                :mounts,
                :cargo,
                :fuel

  def self.fetch_all(token)
    payloads = ApiResource.fetch(RESOURCE_URL, token)
    payloads.map { |payload| new(**payload) }
  end
end

app/models/waypoint.rb
class Waypoint
  include ActiveModel::API

  attr_accessor :symbol, :type, :traits

  def self.fetch_all(system:, traits:, token:)
    payloads =
      ApiResource.fetch(
        "https://api.spacetraders.io/v2/systems/#{system}/waypoints?traits=#{traits}",
        token
      )
    payloads.map { |payload| new(**payload.slice("symbol", "type", "traits")) }
  end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  def index
    @agents = Agent.all
  end

  def show
    @agent = Agent.fetch(current_agent_token)
    respond_to do |format|
      format.json { render json: @agent }
      format.html
    end
  end

  def create
    agent = Agent.register(params[:name])
    set_current_agent(token: agent.token, name: agent.name)
    redirect_to :agent
  end

  def update
    agent = Agent.find_by(name: params[:name])
    set_current_agent(token: agent.token, name: agent.name)
    redirect_to :agent
  end

  def destroy
    Agent.find_by(name: params[:name]).destroy!
    redirect_to :root
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_agent_symbol

  protected

  def current_agent_token
    session[:current_agent_token]
  end

  def current_agent_symbol
    session[:current_agent_symbol]
  end

  def set_current_agent(token:, name:)
    session[:current_agent_token] = token
    session[:current_agent_symbol] = name
  end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  def index
    @contracts = Contract.fetch_all(current_agent_token)
    respond_to do |format|
      format.json {render json: @contracts}
      format.html
    end
  end

  def create
    Contract.accept(params[:id], current_agent_token)
    redirect_to :contracts
  end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  def index
    @ships = Ship.fetch_all(current_agent_token)
    respond_to do |format|
      format.json {render json: @ships}
      format.html
    end
  end
end

app/controllers/waypoints_controller.rb
class WaypointsController < ApplicationController
  def index
    @waypoints =
      Waypoint.fetch_all(
        system: params[:system],
        token: current_agent_token,
        traits: params[:traits]
      )
    respond_to do |format|
      format.json { render json: @waypoints }
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agents/index.html.erb
<ul>
  <% @agents.each do |agent| %>
    <li>
      <p>Name: <%= agent.name %></p>
      <%= link_to "Select", agent_path(name: agent.name), data: { turbo_method: :put } %>
    </li>
  <% end %>
</ul>
<%= form_with url: "/agent", method: :post do |form| %>
  <%= form.label :name, "Name:" %>
  <%= form.text_field :name %>
  <%= form.submit "Register" %>
<% end %>

app/views/agents/show.html.erb
<h2>Account ID: <%= @agent.account_id %></h2>
<h2>Symbol: <%= @agent.symbol %></h2>
<h2>Headquarters: <%= @agent.headquarters %></h2>
<h2>Credits: <%= @agent.credits %></h2>
<h2>Starting Faction: <%= @agent.starting_faction %></h2>
<h2>Ship Count: <%= @agent.ship_count %></h2>

<%= link_to "Delete", agent_path(name: @agent.symbol), data: { turbo_method: :delete } %>

app/views/contracts/index.html.erb
<ul>
  <% @contracts.each do |contract| %>
    <li>
      <p>Faction: <%= contract.faction_symbol %></p>
      <p>Type: <%= contract.type %></p>
      <p>Terms: <pre><%= JSON.pretty_generate(contract.terms) %></pre></p>
      <p>Expiration: <%= contract.expiration %></p>
      <p>Accepted: <%= contract.accepted %></p>
      <% unless contract.accepted %>
        <%= link_to "Accept", contracts_path(id: contract.id), data: { turbo_method: :post } %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpaceTrader</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <ul>
      <li><%= link_to current_agent_symbol, agent_path %></li>
      <li><%= link_to "Contracts", contracts_path %></li>
      <li><%= link_to "Ships", ships_path %></li>
    </ul>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/ships/index.html.erb
<ul>
  <% @ships.each do |ship| %>
    <li>
      <p>Symbol: <%= ship.symbol %></p>
      <div>Registration: <pre><%= JSON.pretty_generate(ship.registration) %></pre></div>
      <div>Navigation: <pre><%= JSON.pretty_generate(ship.nav) %></pre></div>
     <%= link_to "View system waypoints", waypoints_path(system: ship.nav["system_symbol"], traits: "SHIPYARD") %>
    </li>
  <% end %>
</ul>

app/views/waypoints/index.html.erb
<ul>
  <% @waypoints.each do |waypoint| %>
  <li>
    Waypoint: <%= waypoint.symbol %> (<%= waypoint.type %>)
    Traits: <pre>
    <%= waypoint.traits.map do |payload| payload["name"] end %>
  </pre>
  </li>
  <% end %>
</ul>